name: make-test

on: push

jobs:
  test:
    name: test entire repo
    runs-on: ubuntu-20.04

    steps:
      # setup
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version:'3'

      # testing
      - name: make test
        run: make test
