name: make-test

on: push

jobs:
  test:
    name: test entire repo
    runs-on: ubuntu-20.04

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: make test
        run: make test
